// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHjNszoICd6ndY8qQ27s1IIKZgmScgXV8',
    appId: '1:1077165388821:web:7b1f81adbe9e264a8a4a1c',
    messagingSenderId: '1077165388821',
    projectId: 'ewqr3r1',
    authDomain: 'ewqr3r1.firebaseapp.com',
    storageBucket: 'ewqr3r1.firebasestorage.app',
    measurementId: 'G-VF21BQDJPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoa7rxoCfBt4UXRSEcbvREKwi2776E8fE',
    appId: '1:1077165388821:android:a3d71526dd0e229e8a4a1c',
    messagingSenderId: '1077165388821',
    projectId: 'ewqr3r1',
    storageBucket: 'ewqr3r1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OCrk106RwRp2X5ZvYYrBFNEgWCqHDjw',
    appId: '1:1077165388821:ios:dbb27d112ec494218a4a1c',
    messagingSenderId: '1077165388821',
    projectId: 'ewqr3r1',
    storageBucket: 'ewqr3r1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OCrk106RwRp2X5ZvYYrBFNEgWCqHDjw',
    appId: '1:1077165388821:ios:dbb27d112ec494218a4a1c',
    messagingSenderId: '1077165388821',
    projectId: 'ewqr3r1',
    storageBucket: 'ewqr3r1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHjNszoICd6ndY8qQ27s1IIKZgmScgXV8',
    appId: '1:1077165388821:web:04acbca621bb663c8a4a1c',
    messagingSenderId: '1077165388821',
    projectId: 'ewqr3r1',
    authDomain: 'ewqr3r1.firebaseapp.com',
    storageBucket: 'ewqr3r1.firebasestorage.app',
    measurementId: 'G-2ZK9GJG6VR',
  );
}
